#NOTE. be careful to update, some are not compatible like nuget as well
#npm install @auth0/auth0-vue
#npm install @badeball/cypress-cucumber-preprocessor
#npm install @bahmutov/cypress-esbuild-preprocessor
#npm install @jsonforms/core
#npm install @jsonforms/vue
#npm install @jsonforms/vue-vanilla
npm install @progress/kendo-data-query
npm install @progress/kendo-drawing
npm install @progress/kendo-licensing
npm install @progress/kendo-scheduler-vue-wrapper
npm install @progress/kendo-theme-default
npm install @progress/kendo-vue-data-tools
npm install @progress/kendo-vue-dateinputs
npm install @progress/kendo-vue-dialogs
npm install @progress/kendo-vue-dropdowns
npm install @progress/kendo-vue-grid
npm install @progress/kendo-vue-indicators
npm install @progress/kendo-vue-inputs
npm install @progress/kendo-vue-intl
npm install @progress/kendo-vue-listview
npm install @progress/kendo-vue-scheduler
npm install @progress/kendo-vue-tooltip
npm install @progress/kendo-vue-upload
#npm install @sentry/vue
#npm install @tinymce/tinymce-vue
#npm install ajv
#npm install axios
#npm install bootstrap
#npm install cypress
#npm install reflect-metadata
#npm install sass
#npm install tsyringe
#npm install uuid
#npm install vue
#npm install vue-router