#NOTE. be careful to update, some are not compatible like nuget as well#npm uninstall @auth0/auth0-vue
#npm uninstall @badeball/cypress-cucumber-preprocessor
#npm uninstall @bahmutov/cypress-esbuild-preprocessor
#npm uninstall @jsonforms/core
#npm uninstall @jsonforms/vue
#npm uninstall @jsonforms/vue-vanilla
npm uninstall @progress/kendo-data-query
npm uninstall @progress/kendo-drawing
npm uninstall @progress/kendo-licensing
npm uninstall @progress/kendo-scheduler-vue-wrapper
npm uninstall @progress/kendo-theme-default
npm uninstall @progress/kendo-vue-data-tools
npm uninstall @progress/kendo-vue-dateinputs
npm uninstall @progress/kendo-vue-dialogs
npm uninstall @progress/kendo-vue-dropdowns
npm uninstall @progress/kendo-vue-grid
npm uninstall @progress/kendo-vue-indicators
npm uninstall @progress/kendo-vue-inputs
npm uninstall @progress/kendo-vue-intl
npm uninstall @progress/kendo-vue-listview
npm uninstall @progress/kendo-vue-scheduler
npm uninstall @progress/kendo-vue-tooltip
npm uninstall @progress/kendo-vue-upload
#npm uninstall @sentry/vue
#npm uninstall @tinymce/tinymce-vue
#npm uninstall ajv
#npm uninstall axios
#npm uninstall bootstrap
#npm uninstall cypress
#npm uninstall reflect-metadata
#npm uninstall sass
#npm uninstall tsyringe
#npm uninstall uuid
#npm uninstall vue
#npm uninstall vue-router