on: push
  # push:
  #   paths:
  #     - vue.jsonforms/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: stefanoeb/eslint-action@1.0.2