on: 
  push:
    paths:
      - vue.jsonforms/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: sudo npm install --unsafe-perm=true --allow-root
      - run: sudo npm run lint