on: push
  # push:
  #   paths:
  #     - vue.jsonforms/**
jobs:
  build-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint