on: push
  # push:
  #   paths:
  #     - vue.jsonforms/**
jobs:
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: npm install eslint
      - run: npm run lint

  run-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - run: npm install vite vue-tsc
      - run: npm run build