on: push
  # push:
  #   paths:
  #     - vue.jsonforms/**
jobs:
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g eslint
      - run: npm run lint

  run-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vue.jsonforms
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vue-tsc vite
      - run: npm run build